# Generated by Django 3.2.6 on 2022-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_Number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('date_available', models.DateTimeField(blank=True)),
                ('desired_pay', models.CharField(blank=True, max_length=50)),
                ('website_blog_portfolio', models.CharField(blank=True, max_length=50)),
                ('linkedin_Profile_URL', models.CharField(blank=True, max_length=50)),
                ('resume', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'JobApplication',
                'verbose_name_plural': 'job_application',
            },
        ),
    ]
