# Generated by Django 3.2.6 on 2022-12-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobApplications',
            options={'verbose_name': 'JobApplication', 'verbose_name_plural': 'jobApplication'},
        ),
    ]
