# Generated by Django 3.2.6 on 2022-12-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_jobapplications_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplications',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
    ]
