# Generated by Django 3.2.6 on 2023-01-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_jobapplications_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='date_available',
            new_name='date',
        ),
    ]
