# Generated by Django 3.2.6 on 2022-08-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
