# Generated by Django 3.2.6 on 2022-09-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_alter_contract_contract_details"),
        ("business_analysis", "0002_auto_20220826_0925"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="income",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="people",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="hr.staff"),
        ),
    ]
