# Generated by Django 3.2.6 on 2022-09-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_analysis', '0003_auto_20220922_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='income',
            field=models.FloatField(blank=True),
        ),
    ]
