# Generated by Django 3.2.6 on 2022-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_alter_broadcast_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
