# Generated by Django 3.2.6 on 2022-11-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_alter_broadcast_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'Broadcast', 'verbose_name_plural': 'Broadcasts'},
        ),
    ]
