# Generated by Django 3.2.6 on 2022-08-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inventory',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
