# Generated by Django 3.2.6 on 2022-08-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_auto_20220812_0900"),
        ("resources", "0004_alter_item_inventory"),
    ]

    operations = []
