# Generated by Django 3.2.6 on 2022-08-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20220812_1131'),
        ('resources', '0005_merge_20220812_0910'),
        ('resources', '0006_alter_item_inventory'),
    ]

    operations = [
    ]
