# Generated by Django 3.2.6 on 2022-08-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_auto_20220822_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="date_of_purchase",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="cost",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
