# Generated by Django 3.2.6 on 2022-10-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_audittrail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audittrail",
            options={},
        ),
    ]
