# Generated by Django 3.2.6 on 2022-10-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_inventory_project"),
        ("resources", "0012_alter_audittrail_options"),
    ]

    operations = []
