# Generated by Django 3.2.6 on 2022-11-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_auto_20221019_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={'ordering': ['-created_at'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
