# Generated by Django 3.2.6 on 2022-07-31 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('state_of_origin', models.CharField(blank=True, choices=[('Abia', 'abia'), ('Adamawa', 'adamawa'), ('Akwa Ibom', 'akwa Ibom'), ('Anambra', 'anambra'), ('Bauchi', 'bauchi'), ('Bayelsa', 'bayelsa'), ('Benue', 'benue'), ('Borno', 'borno'), ('Cross River', 'cross river'), ('Delta', 'delta'), ('Ebonyi', 'ebonyi'), ('Edo', 'edo'), ('Ekiti', 'ekiti'), ('Enugu', 'enugu'), ('Gombe', 'gombe'), ('Imo', 'imo'), ('Jigawa', 'jigawa'), ('Kaduna', 'kaduna'), ('Kano', 'kano'), ('Katsina', 'katsina'), ('Kebbi', 'kebbi'), ('Kogi', 'kogi'), ('Kwara', 'kwara'), ('Lagos', 'lagos'), ('Nasarawa', 'nasarawa'), ('Niger', 'niger'), ('Ogun', 'ogun'), ('Ondo', 'ondo'), ('Osun', 'osun'), ('Oyo', 'oyo'), ('Plateau', 'plateau'), ('Rivers', 'rivers'), ('Sokoto', 'sokoto'), ('Taraba', 'taraba'), ('Yobe', 'yobe'), ('Zamfara', 'zamfara')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone_no', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('tnstagram', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedIn', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_ID', models.CharField(blank=True, max_length=200)),
                ('commencement_Date', models.DateTimeField(blank=True, max_length=200)),
                ('salary', models.IntegerField(blank=True)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, choices=[('Accounting', 'accounting'), ('Human Resources', 'human resources'), ('Developers', 'developers'), ('Business Analysis', 'business analysis'), ('Business Development', 'business development')], max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
        ),
    ]
