# Generated by Django 3.2.6 on 2022-08-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
