# Generated by Django 3.2.6 on 2022-08-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_staff_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='commencement_Date',
            new_name='commencement_date',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_ID',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
