# Generated by Django 3.2.6 on 2022-08-11 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(blank=True, max_length=5)),
                ('description', models.TextField(blank=True)),
                ('account_class', models.CharField(blank=True, choices=[('revenue', 'Revenue'), ('equity', 'Equity'), ('other income', 'Other Income'), ('other expense', 'Other Expense')], max_length=20)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField(null=True)),
                ('account_code', models.CharField(max_length=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('dr', models.IntegerField(blank=True, null=True)),
                ('cr', models.IntegerField(blank=True, null=True)),
                ('agent_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
            },
        ),
    ]
