# Generated by Django 3.2.6 on 2022-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
