# Generated by Django 3.2.6 on 2022-08-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_account_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(blank=True, choices=[("cr", "CR"), ("dr", "DR")], max_length=20),
        ),
    ]
