# Generated by Django 3.2.6 on 2022-08-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(blank=True, choices=[("cr", "CR"), ("dr", "DR")], max_length=20, null=True),
        ),
    ]
