# Generated by Django 3.2.6 on 2022-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='cr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='dr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
