# Generated by Django 3.2.6 on 2022-11-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
