# Generated by Django 3.2.6 on 2022-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_length",
            field=models.IntegerField(blank=True, max_length=200),
        ),
    ]
