# Generated by Django 3.2.6 on 2022-11-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20221019_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-created_at'], 'permissions': [], 'verbose_name': 'staff', 'verbose_name_plural': 'staff'},
        ),
    ]
