# Generated by Django 3.2.6 on 2022-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20221121_1104'),
        ('hr', '0008_leave'),
    ]

    operations = [
    ]
