# Generated by Django 3.2.6 on 2022-11-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_merge_0008_auto_20221121_1104_0008_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(auto_now=True)),
                ('incidence_report_date', models.DateField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
