# Generated by Django 3.2.6 on 2022-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], max_length=200, null=True),
        ),
    ]
